# Form implementation generated from reading ui file '.\ui\alert.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 697)
        Form.setStyleSheet("border-radius:8px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(parent=Form)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget_4)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../sources/alert-svgrepo-com.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(200, 200))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.voltar = QtWidgets.QPushButton(parent=self.widget_2)
        self.voltar.setMinimumSize(QtCore.QSize(250, 80))
        self.voltar.setMaximumSize(QtCore.QSize(250, 80))
        self.voltar.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF;       /* Azul padrão iOS */\n"
"    color: white;\n"
"    border-radius: 12px;             /* iOS usa bordas mais suaves */\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;                /* semi-bold padrão iOS */\n"
"    border: none;                    /* sem borda visível */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0A84FF;       /* Azul iOS Hover – levemente mais claro */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0063CC;       /* Azul iOS Pressed – um pouco mais escuro */\n"
"}\n"
"")
        self.voltar.setObjectName("voltar")
        self.verticalLayout_4.addWidget(self.voltar)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4.addWidget(self.widget_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#2776dd;\">Selecione seu fogão</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#ff0000;\">ATENÇÃO<br/>ALERTA DE CHAMA LIGADA<br/></span><span style=\" font-size:16pt; font-weight:600; color:#7600ff;\">Fogão #Fogao na Boca #Boca<br/><br/></span><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">Desligamento automático</span></p></body></html>"))
        self.voltar.setText(_translate("Form", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
