# Form implementation generated from reading ui file '.\ui\config.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 714)
        Form.setStyleSheet("border-radius:8px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(parent=Form)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.u_name = QtWidgets.QLineEdit(parent=self.widget_11)
        self.u_name.setMinimumSize(QtCore.QSize(0, 30))
        self.u_name.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.u_name.setReadOnly(True)
        self.u_name.setPlaceholderText("")
        self.u_name.setObjectName("u_name")
        self.verticalLayout_12.addWidget(self.u_name)
        self.u_email = QtWidgets.QLineEdit(parent=self.widget_11)
        self.u_email.setMinimumSize(QtCore.QSize(0, 30))
        self.u_email.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.u_email.setReadOnly(True)
        self.u_email.setPlaceholderText("")
        self.u_email.setObjectName("u_email")
        self.verticalLayout_12.addWidget(self.u_email)
        self.widget_12 = QtWidgets.QWidget(parent=self.widget_11)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.logout = QtWidgets.QPushButton(parent=self.widget_12)
        self.logout.setMinimumSize(QtCore.QSize(250, 50))
        self.logout.setMaximumSize(QtCore.QSize(250, 50))
        self.logout.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF;       /* Azul padrão iOS */\n"
"    color: white;\n"
"    border-radius: 12px;             /* iOS usa bordas mais suaves */\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;                /* semi-bold padrão iOS */\n"
"    border: none;                    /* sem borda visível */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0A84FF;       /* Azul iOS Hover – levemente mais claro */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0063CC;       /* Azul iOS Pressed – um pouco mais escuro */\n"
"}\n"
"")
        self.logout.setObjectName("logout")
        self.verticalLayout_13.addWidget(self.logout)
        self.verticalLayout_12.addWidget(self.widget_12, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_11)
        self.label = QtWidgets.QLabel(parent=self.widget_4)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.notifica_gen = QtWidgets.QCheckBox(parent=self.widget_6)
        self.notifica_gen.setStyleSheet("QCheckBox {\n"
"    font-size: 16px;\n"
"    color: #1C1C1E;\n"
"    spacing: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 4px;\n"
"    border: 2px solid #D1D1D6;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"/* Força preenchimento total quando marcado */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #007AFF;   /* fundo azul */\n"
"    border: 2px solid #007AFF;   /* borda azul */\n"
"    image: none;                 /* remove o ✓ padrão */\n"
"}\n"
"")
        self.notifica_gen.setObjectName("notifica_gen")
        self.verticalLayout_7.addWidget(self.notifica_gen)
        self.verticalLayout_6.addWidget(self.widget_6, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_9.setSpacing(15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.not_fs = QtWidgets.QCheckBox(parent=self.widget_9)
        self.not_fs.setStyleSheet("QCheckBox {\n"
"    font-size: 16px;\n"
"    color: #1C1C1E;\n"
"    spacing: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 4px;\n"
"    border: 2px solid #D1D1D6;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"/* Força preenchimento total quando marcado */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #007AFF;   /* fundo azul */\n"
"    border: 2px solid #007AFF;   /* borda azul */\n"
"    image: none;                 /* remove o ✓ padrão */\n"
"}\n"
"")
        self.not_fs.setObjectName("not_fs")
        self.verticalLayout_9.addWidget(self.not_fs)
        self.time_1 = QtWidgets.QLineEdit(parent=self.widget_9)
        self.time_1.setMinimumSize(QtCore.QSize(0, 30))
        self.time_1.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.time_1.setObjectName("time_1")
        self.verticalLayout_9.addWidget(self.time_1)
        self.verticalLayout_8.addWidget(self.widget_9, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.not_f = QtWidgets.QCheckBox(parent=self.widget_10)
        self.not_f.setStyleSheet("QCheckBox {\n"
"    font-size: 16px;\n"
"    color: #1C1C1E;\n"
"    spacing: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 4px;\n"
"    border: 2px solid #D1D1D6;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"/* Força preenchimento total quando marcado */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #007AFF;   /* fundo azul */\n"
"    border: 2px solid #007AFF;   /* borda azul */\n"
"    image: none;                 /* remove o ✓ padrão */\n"
"}\n"
"")
        self.not_f.setObjectName("not_f")
        self.verticalLayout_10.addWidget(self.not_f)
        self.time_2 = QtWidgets.QLineEdit(parent=self.widget_10)
        self.time_2.setMinimumSize(QtCore.QSize(0, 30))
        self.time_2.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.time_2.setObjectName("time_2")
        self.verticalLayout_10.addWidget(self.time_2)
        self.verticalLayout_8.addWidget(self.widget_10)
        self.verticalLayout_6.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.salvar = QtWidgets.QPushButton(parent=self.widget_7)
        self.salvar.setMinimumSize(QtCore.QSize(250, 50))
        self.salvar.setMaximumSize(QtCore.QSize(250, 50))
        self.salvar.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF;       /* Azul padrão iOS */\n"
"    color: white;\n"
"    border-radius: 12px;             /* iOS usa bordas mais suaves */\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;                /* semi-bold padrão iOS */\n"
"    border: none;                    /* sem borda visível */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0A84FF;       /* Azul iOS Hover – levemente mais claro */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0063CC;       /* Azul iOS Pressed – um pouco mais escuro */\n"
"}\n"
"")
        self.salvar.setObjectName("salvar")
        self.verticalLayout_11.addWidget(self.salvar)
        self.verticalLayout_6.addWidget(self.widget_7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.voltar = QtWidgets.QPushButton(parent=self.widget_2)
        self.voltar.setMinimumSize(QtCore.QSize(250, 80))
        self.voltar.setMaximumSize(QtCore.QSize(250, 80))
        self.voltar.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF;       /* Azul padrão iOS */\n"
"    color: white;\n"
"    border-radius: 12px;             /* iOS usa bordas mais suaves */\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;                /* semi-bold padrão iOS */\n"
"    border: none;                    /* sem borda visível */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0A84FF;       /* Azul iOS Hover – levemente mais claro */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0063CC;       /* Azul iOS Pressed – um pouco mais escuro */\n"
"}\n"
"")
        self.voltar.setObjectName("voltar")
        self.verticalLayout_4.addWidget(self.voltar)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4.addWidget(self.widget_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#2776dd;\">CONTA</span></p></body></html>"))
        self.logout.setText(_translate("Form", "SAIR"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#2776dd;\">CONFIGURAÇÕES</span></p></body></html>"))
        self.notifica_gen.setText(_translate("Form", "HABILITAR NOFIFICAÇÕES"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#2776dd;\">Alerta sobre fogo ligado sem panela</span></p></body></html>"))
        self.not_fs.setText(_translate("Form", "HABILITAR"))
        self.time_1.setPlaceholderText(_translate("Form", "Tempo em segundos"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#2776dd;\">Alerta sobre tempo de fogo ligado</span></p></body></html>"))
        self.not_f.setText(_translate("Form", "HABILITAR"))
        self.time_2.setPlaceholderText(_translate("Form", "Tempo em minutos"))
        self.salvar.setText(_translate("Form", "SALVAR"))
        self.voltar.setText(_translate("Form", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
