# Form implementation generated from reading ui file '.\ui\login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 714)
        Form.setStyleSheet("border-radius:8px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(parent=Form)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.nome = QtWidgets.QLineEdit(parent=self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nome.sizePolicy().hasHeightForWidth())
        self.nome.setSizePolicy(sizePolicy)
        self.nome.setMinimumSize(QtCore.QSize(0, 30))
        self.nome.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.nome.setPlaceholderText("")
        self.nome.setObjectName("nome")
        self.horizontalLayout.addWidget(self.nome)
        self.verticalLayout_8.addWidget(self.widget_9, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_11)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.email = QtWidgets.QLineEdit(parent=self.widget_11)
        self.email.setMinimumSize(QtCore.QSize(0, 30))
        self.email.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.email.setPlaceholderText("")
        self.email.setObjectName("email")
        self.horizontalLayout_2.addWidget(self.email)
        self.verticalLayout_8.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_12)
        self.label_5.setMinimumSize(QtCore.QSize(50, 0))
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.password = QtWidgets.QLineEdit(parent=self.widget_12)
        self.password.setMinimumSize(QtCore.QSize(0, 30))
        self.password.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.password.setPlaceholderText("")
        self.password.setObjectName("password")
        self.horizontalLayout_3.addWidget(self.password)
        self.verticalLayout_8.addWidget(self.widget_12)
        self.widget = QtWidgets.QWidget(parent=self.widget_8)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.create = QtWidgets.QPushButton(parent=self.widget)
        self.create.setMinimumSize(QtCore.QSize(250, 80))
        self.create.setMaximumSize(QtCore.QSize(250, 80))
        self.create.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF;       /* Azul padrão iOS */\n"
"    color: white;\n"
"    border-radius: 12px;             /* iOS usa bordas mais suaves */\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;                /* semi-bold padrão iOS */\n"
"    border: none;                    /* sem borda visível */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0A84FF;       /* Azul iOS Hover – levemente mais claro */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0063CC;       /* Azul iOS Pressed – um pouco mais escuro */\n"
"}\n"
"")
        self.create.setObjectName("create")
        self.horizontalLayout_6.addWidget(self.create)
        self.verticalLayout_8.addWidget(self.widget)
        self.verticalLayout_6.addWidget(self.widget_8, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.widget_14 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.widget_14, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.email_2 = QtWidgets.QLineEdit(parent=self.widget_10)
        self.email_2.setMinimumSize(QtCore.QSize(0, 30))
        self.email_2.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.email_2.setPlaceholderText("")
        self.email_2.setObjectName("email_2")
        self.horizontalLayout_5.addWidget(self.email_2)
        self.verticalLayout_7.addWidget(self.widget_10)
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.password_2 = QtWidgets.QLineEdit(parent=self.widget_13)
        self.password_2.setMinimumSize(QtCore.QSize(0, 30))
        self.password_2.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;        /* fundo branco iOS */\n"
"    color: #1C1C1E;                   /* texto preto iOS */\n"
"    border: 1.5px solid #D1D1D6;      /* cinza leve iOS */\n"
"    border-radius: 10px;              /* canto arredondado iOS */\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #007AFF;      /* azul iOS quando focado */\n"
"    outline: none;\n"
"}")
        self.password_2.setPlaceholderText("")
        self.password_2.setObjectName("password_2")
        self.horizontalLayout_4.addWidget(self.password_2)
        self.verticalLayout_7.addWidget(self.widget_13)
        self.widget_15 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.login = QtWidgets.QPushButton(parent=self.widget_15)
        self.login.setMinimumSize(QtCore.QSize(250, 80))
        self.login.setMaximumSize(QtCore.QSize(250, 80))
        self.login.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF;       /* Azul padrão iOS */\n"
"    color: white;\n"
"    border-radius: 12px;             /* iOS usa bordas mais suaves */\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;                /* semi-bold padrão iOS */\n"
"    border: none;                    /* sem borda visível */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0A84FF;       /* Azul iOS Hover – levemente mais claro */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0063CC;       /* Azul iOS Pressed – um pouco mais escuro */\n"
"}\n"
"")
        self.login.setObjectName("login")
        self.verticalLayout_9.addWidget(self.login)
        self.verticalLayout_7.addWidget(self.widget_15, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addWidget(self.widget_7, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6.addWidget(self.widget_6)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4.addWidget(self.widget_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#2776dd;\">CRIAR UMA CONTA</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#2776dc;\">Nome</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#2776dc;\">Email</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#2776dc;\">Senha</span></p></body></html>"))
        self.create.setText(_translate("Form", "CRIAR CONTA"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#2776dd;\">OU</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#2776dd;\">ENTRAR</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#2776dc;\">Email</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#2776dc;\">Senha</span></p></body></html>"))
        self.login.setText(_translate("Form", "ACESSAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
